# Generated by Django 5.2.6 on 2025-09-19 10:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код страны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название фабрики')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для отправки заказов')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Фабрика',
                'verbose_name_plural': 'Фабрики',
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название заказа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('excel_file', models.FileField(upload_to='orders/excel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])], verbose_name='Excel файл заказа')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='orders/invoices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF файл инвойса')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('sent', 'Отправлен'), ('invoice_received', 'Инвойс получен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('invoice_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения инвойса')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('factory_comments', models.TextField(blank=True, verbose_name='Комментарии фабрики')),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание')),
                ('reminder_count', models.PositiveIntegerField(default=0, verbose_name='Количество напоминаний')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.factory', verbose_name='Фабрика')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
