# Generated by Django 5.2.6 on 2025-09-19 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('uploaded_reminder', 'Напоминание о неотправленном заказе'), ('sent_reminder', 'Напоминание о заказе без инвойса'), ('invoice_received', 'Инвойс получен'), ('order_sent', 'Заказ отправлен'), ('order_completed', 'Заказ завершен')], max_length=20, unique=True, verbose_name='Тип шаблона')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('html_template', models.TextField(verbose_name='HTML шаблон')),
                ('text_template', models.TextField(verbose_name='Текстовый шаблон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('uploaded_reminder', 'Напоминание о неотправленном заказе'), ('sent_reminder', 'Напоминание о заказе без инвойса'), ('invoice_received', 'Инвойс получен'), ('order_sent', 'Заказ отправлен'), ('order_completed', 'Заказ завершен')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('reminder_frequency', models.PositiveIntegerField(default=7, help_text='Количество дней между напоминаниями', verbose_name='Частота напоминаний (дни)')),
                ('notify_uploaded_reminder', models.BooleanField(default=True, verbose_name='Напоминания о неотправленных заказах')),
                ('notify_sent_reminder', models.BooleanField(default=True, verbose_name='Напоминания о заказах без инвойса')),
                ('notify_invoice_received', models.BooleanField(default=True, verbose_name='Уведомления о получении инвойса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
