# Generated by Django 5.1.4 on 2025-09-21 07:47

import django.core.validators
import orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_notificationtemplate_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='excel_file',
            field=models.FileField(upload_to='orders/excel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls']), orders.validators.validate_excel_file], verbose_name='Excel файл заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/invoices/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), orders.validators.validate_pdf_file], verbose_name='PDF файл инвойса'),
        ),
    ]
