# Generated by Django 5.1.4 on 2025-09-24 09:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_fix_existing_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_uploaded', 'Заказ загружен'), ('order_sent', 'Заказ отправлен'), ('invoice_received', 'Инвойс получен'), ('order_completed', 'Заказ завершен'), ('uploaded_reminder', 'Напоминание о неотправленном заказе'), ('sent_reminder', 'Напоминание о заказе без инвойса')], max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_invoice_received',
            field=models.BooleanField(default=True, help_text='Получать уведомления когда фабрика загружает инвойс', verbose_name='Уведомления о получении инвойса'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_sent_reminder',
            field=models.BooleanField(default=True, help_text='Получать напоминания о заказах, которые отправлены но инвойс не получен', verbose_name='Напоминания о заказах без инвойса'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_uploaded_reminder',
            field=models.BooleanField(default=True, help_text='Получать напоминания о заказах, которые загружены но не отправлены', verbose_name='Напоминания о неотправленных заказах'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Уникальный номер инвойса от фабрики', max_length=100, verbose_name='Номер инвойса')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Полная сумма по инвойсу', max_digits=12, verbose_name='Общая сумма к оплате')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма всех платежей')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Остаток к доплате')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('partial', 'Частично оплачен'), ('paid', 'Полностью оплачен'), ('overdue', 'Просрочен')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('due_date', models.DateField(blank=True, help_text='Дата, до которой должен быть оплачен инвойс', null=True, verbose_name='Срок оплаты')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарии')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Инвойс',
                'verbose_name_plural': 'Инвойсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма платежа')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('payment_type', models.CharField(choices=[('deposit', 'Депозит'), ('final_payment', 'Финальный платеж'), ('partial_payment', 'Частичный платеж'), ('refund', 'Возврат')], default='partial_payment', max_length=20, verbose_name='Тип платежа')),
                ('payment_receipt', models.FileField(help_text='Фото или скриншот подтверждения оплаты', upload_to='payments/receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Скриншот чека оплаты')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о платеже', verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.invoice', verbose_name='Инвойс')),
            ],
            options={
                'verbose_name': 'Платеж по инвойсу',
                'verbose_name_plural': 'Платежи по инвойсам',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлен'), ('status_changed', 'Изменен статус'), ('file_uploaded', 'Загружен файл'), ('file_downloaded', 'Скачан файл'), ('sent', 'Отправлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('deleted', 'Удален')], max_length=20, verbose_name='Действие')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('field_name', models.CharField(blank=True, max_length=50, verbose_name='Поле')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('send_order', 'Отправка заказа'), ('upload_invoice', 'Загрузка инвойса'), ('complete_order', 'Завершение заказа'), ('cancel_order', 'Отмена заказа'), ('delete_order', 'Удаление заказа')], max_length=20, verbose_name='Действие')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус')),
                ('confirmation_data', models.JSONField(default=dict, verbose_name='Данные подтверждения')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Запрошено')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждено')),
                ('expires_at', models.DateTimeField(help_text='Автоматически устанавливается при создании', verbose_name='Истекает')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_actions', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Запросил')),
            ],
            options={
                'verbose_name': 'Подтверждение операции',
                'verbose_name_plural': 'Подтверждения операций',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Отдел')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['user__username'],
            },
        ),
    ]
