# Generated by Django 5.1.4 on 2025-09-24 09:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_fake_existing_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_uploaded', 'Заказ загружен'), ('order_sent', 'Заказ отправлен'), ('invoice_received', 'Инвойс получен'), ('order_completed', 'Заказ завершен'), ('uploaded_reminder', 'Напоминание о неотправленном заказе'), ('sent_reminder', 'Напоминание о заказе без инвойса')], max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_invoice_received',
            field=models.BooleanField(default=True, help_text='Получать уведомления когда фабрика загружает инвойс', verbose_name='Уведомления о получении инвойса'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_sent_reminder',
            field=models.BooleanField(default=True, help_text='Получать напоминания о заказах, которые отправлены но инвойс не получен', verbose_name='Напоминания о заказах без инвойса'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_uploaded_reminder',
            field=models.BooleanField(default=True, help_text='Получать напоминания о заказах, которые загружены но не отправлены', verbose_name='Напоминания о неотправленных заказах'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Уникальный номер инвойса от фабрики', max_length=100, verbose_name='Номер инвойса')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Полная сумма по инвойсу', max_digits=12, verbose_name='Общая сумма к оплате')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма всех платежей')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Остаток к доплате')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('partial', 'Частично оплачен'), ('paid', 'Полностью оплачен'), ('overdue', 'Просрочен')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('due_date', models.DateField(blank=True, help_text='Дата, до которой должен быть оплачен инвойс', null=True, verbose_name='Срок оплаты')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарии')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Инвойс',
                'verbose_name_plural': 'Инвойсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма платежа')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('payment_type', models.CharField(choices=[('deposit', 'Депозит'), ('final_payment', 'Финальный платеж'), ('partial_payment', 'Частичный платеж'), ('refund', 'Возврат')], default='partial_payment', max_length=20, verbose_name='Тип платежа')),
                ('payment_receipt', models.FileField(help_text='Фото или скриншот подтверждения оплаты', upload_to='payments/receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Скриншот чека оплаты')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о платеже', verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.invoice', verbose_name='Инвойс')),
            ],
            options={
                'verbose_name': 'Платеж по инвойсу',
                'verbose_name_plural': 'Платежи по инвойсам',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
