# Generated by Django 5.1.4 on 2025-09-29 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Удобное название для идентификации шаблона', max_length=100, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('factory_order', 'Заказ на фабрику'), ('reminder', 'Напоминание'), ('confirmation', 'Подтверждение'), ('invoice_request', 'Запрос инвойса')], default='factory_order', max_length=20, verbose_name='Тип шаблона')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('de', 'Deutsch'), ('it', 'Italiano'), ('tr', 'Türkçe'), ('pl', 'Polski'), ('cz', 'Čeština'), ('cn', '中文'), ('lt', 'Lietuvių')], default='ru', max_length=5, verbose_name='Язык')),
                ('subject', models.CharField(help_text='Используйте переменные: {{ order.title }}, {{ factory.name }}', max_length=200, verbose_name='Тема письма')),
                ('html_content', models.TextField(help_text='HTML версия письма с поддержкой переменных', verbose_name='HTML содержимое')),
                ('text_content', models.TextField(help_text='Текстовая версия письма для клиентов без поддержки HTML', verbose_name='Текстовое содержимое')),
                ('is_active', models.BooleanField(default=True, help_text='Только активные шаблоны используются при отправке', verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, help_text='Шаблон по умолчанию для данного типа и языка', verbose_name='По умолчанию')),
                ('description', models.TextField(blank=True, help_text='Описание назначения и особенностей шаблона', verbose_name='Описание')),
                ('variables_help', models.TextField(blank=True, help_text='Список доступных переменных для использования в шаблоне', verbose_name='Справка по переменным')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Email шаблон',
                'verbose_name_plural': 'Email шаблоны',
                'ordering': ['template_type', 'language', 'name'],
                'unique_together': {('template_type', 'language', 'is_default')},
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('html_content', models.TextField(verbose_name='HTML содержимое')),
                ('text_content', models.TextField(verbose_name='Текстовое содержимое')),
                ('change_description', models.TextField(blank=True, verbose_name='Описание изменений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='orders.emailtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Версия шаблона',
                'verbose_name_plural': 'Версии шаблонов',
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
    ]
