# Generated by Django 5.1.4 on 2025-09-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_emailtemplate_emailtemplateversion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('factory_order', 'Заказ на фабрику'), ('order_confirmation', 'Подтверждение заказа'), ('order_notification', 'Уведомление о заказе'), ('reminder', 'Напоминание'), ('confirmation', 'Подтверждение'), ('invoice_request', 'Запрос инвойса')], default='factory_order', max_length=20, verbose_name='Тип шаблона'),
        ),
    ]
