# Generated by Django 5.1.4 on 2025-09-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_emailtemplate_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('factory_order', 'Заказ на фабрику'), ('order_confirmation', 'Подтверждение заказа'), ('order_notification', 'Уведомление о заказе'), ('reminder', 'Напоминание'), ('confirmation', 'Подтверждение'), ('invoice_request', 'Запрос инвойса')], default='order_confirmation', max_length=20, verbose_name='Тип шаблона'),
        ),
    ]
