# Generated by Django 5.1.4 on 2025-11-07 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_change_default_template_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCBM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbm_value', models.DecimalField(decimal_places=3, help_text='Объем в кубических метрах', max_digits=10, verbose_name='CBM')),
                ('date', models.DateField(help_text='Дата добавления CBM', verbose_name='Дата')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о CBM', verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cbm_records', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbm_records', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Запись CBM',
                'verbose_name_plural': 'Записи CBM',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
