# Generated by Django 5.1.4 on 2025-11-11 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_create_missing_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(help_text='Уникальный номер фуры/отправки', max_length=100, unique=True, verbose_name='Номер фуры')),
                ('received_cbm', models.DecimalField(blank=True, decimal_places=3, help_text='Фактически полученные кубы в фуре', max_digits=10, null=True, verbose_name='Фактические кубы')),
                ('shipment_date', models.DateField(blank=True, help_text='Дата отправки фуры', null=True, verbose_name='Дата отправки')),
                ('received_date', models.DateField(blank=True, help_text='Дата получения товара', null=True, verbose_name='Дата получения')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о фуре', verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('orders', models.ManyToManyField(help_text='Заказы, которые входят в эту фуру', related_name='shipments', to='orders.order', verbose_name='Заказы')),
            ],
            options={
                'verbose_name': 'Фура',
                'verbose_name_plural': 'Фуры',
                'ordering': ['-shipment_date', '-created_at'],
            },
        ),
    ]
