# Generated by Django 5.1.4 on 2025-12-05 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_add_shipment_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_by_client',
            field=models.BooleanField(default=False, verbose_name='Отменен клиентом'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by_client_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены клиентом'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by_client_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL, verbose_name='Отменил клиентом'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by_client_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий при отмене клиентом'),
        ),
    ]
