# Generated by Django 5.1.4 on 2025-12-05 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_cancelled_by_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cancelled_by_client'], name='order_cancelled_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cancelled_by_client_at'], name='order_cancelled_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cancelled_by_client', 'cancelled_by_client_at'], name='order_cancelled_comp_idx'),
        ),
    ]
