# Generated by Django 5.1.4 on 2025-12-08 05:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_order_cancelled_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='e_factura_turkey',
            field=models.BooleanField(default=False, verbose_name='E-Factura Turkey'),
        ),
        migrations.AddField(
            model_name='order',
            name='factura_export',
            field=models.BooleanField(default=False, verbose_name='Factura Export'),
        ),
        migrations.CreateModel(
            name='EFacturaBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Январь 2025, Февраль 2026', max_length=100, verbose_name='Название корзины')),
                ('month', models.PositiveIntegerField(help_text='Номер месяца (1-12)', verbose_name='Месяц')),
                ('year', models.PositiveIntegerField(help_text='Год (например, 2025)', verbose_name='Год')),
                ('basket_date', models.DateField(help_text='Дата, связанная с корзиной', verbose_name='Дата корзины')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о корзине', verbose_name='Комментарии')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_efactura_baskets', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Корзина E-Factura',
                'verbose_name_plural': 'Корзины E-Factura',
                'ordering': ['-year', '-month', '-created_at'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EFacturaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='efactura/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xml', 'xlsx', 'xls'])], verbose_name='Файл E-Factura')),
                ('upload_date', models.DateField(help_text='Дата загрузки файла', verbose_name='Дата загрузки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о файле', verbose_name='Комментарии')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.efacturabasket', verbose_name='Корзина')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_efactura_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efactura_files', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Файл E-Factura',
                'verbose_name_plural': 'Файлы E-Factura',
                'ordering': ['-upload_date', '-created_at'],
            },
        ),
    ]
