# Generated by Django 5.1.4 on 2025-12-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_e_factura_turkey_order_factura_export_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='efacturafile',
            unique_together={('order', 'basket')},
        ),
    ]
