# Generated by Django 5.1.4 on 2025-12-08 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_add_unique_together_efactura_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='efacturabasket',
            index=models.Index(fields=['year', 'month'], name='efactura_basket_ym_idx'),
        ),
        migrations.AddIndex(
            model_name='efacturabasket',
            index=models.Index(fields=['created_by'], name='efactura_basket_cb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='inv_status_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['order'], name='invoice_order_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['uploaded_at'], name='order_uploaded_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['employee'], name='order_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['factory'], name='order_factory_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'uploaded_at'], name='order_status_upld_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['employee', 'status'], name='order_empl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='orderconfirmation',
            index=models.Index(fields=['status', 'expires_at'], name='conf_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='orderconfirmation',
            index=models.Index(fields=['order', 'status'], name='conf_order_status_idx'),
        ),
    ]
