# Generated by Django 5.1.4 on 2025-12-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='factory_reminder_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество напоминаний фабрике'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_factory_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Дата последнего напоминания фабрике о необходимости загрузить инвойс', null=True, verbose_name='Последнее напоминание фабрике'),
        ),
    ]
